name: Pages
description: Welcome to My Website
remote_theme: pages-themes/midnight
source: docs
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
defaults:
  - scope:
      path: ""
    values:
      layout: "default"